### ISSUE TITLE
Suggestions for improving documentation

### ISSUE THREAD

**Issue by desilinguist** [tresoldi/dafsa#3]
The documentation is really nice! I have a few suggestion to make it even better:

1. Provide a clear statement-of-need like you do in the JOSS paper.
2. Provide a full walkthrough of the first example you provide in the "How to use" section. For example, it is not clear what all the numbers and symbols mean. It would be nice if you take one line of the example output and document what each symbol means.
3. It would also be nice if you could provide a fully worked-through realistic example. For example, the phonemes example is pretty nice but it isn't really clear (other than to phoneticians) what the various strings mean.

**Comment by tresoldi** [comment]
First item is done, a draft of the second is on-going ([here](https://github.com/tresoldi/dafsa/blob/joss/docs/quickstart.rst)), and the third one is pending.

Unfortunately I found a bug while writing the documentation, of the kind that seems to be only triggered in specific situations and thus a bit harder to debug. I will work on it tomorrow (one more example that documentation is good for finding bugs...).

**Comment by tresoldi** [comment]
@desilinguist please check: https://dafsa.readthedocs.io/en/latest/quickstart.html

**Comment by desilinguist** [comment]
Fantastic! Thanks again!
