### ISSUE TITLE
Please provide explicit list of dependencies

### ISSUE THREAD

**Issue by desilinguist** [tresoldi/dafsa#4]
1. It would be great if you could explicitly list the dependencies in the README.
2. Please use a `requirements.txt` file rather than just listing the dependencies in `setup.py`.

**Comment by geoffbacon** [comment]
I'm also in favour of these two suggestions. Indeed, the fact that dafsa only has one third party dependency (networkx) is a strong positive. Potential users will have more confidence that the installation will "just work".

**Comment by tresoldi** [comment]
Done and tested in a different branch. I'll comment again once I merge in `master`.

**Comment by tresoldi** [comment]
@desilinguist and @geoffbacon : implemented and published in the new version 0.6. Please close the issue if it is ok.

**Comment by geoffbacon** [comment]
I don't have privilege to close but looks great to me.

**Comment by tresoldi** [comment]
Great, thank you! I'll wait for @desilinguist to close the issue.

**Comment by desilinguist** [comment]
Looks great. Thanks!
