### ISSUE TITLE
Please consider creating a conda package 

### ISSUE THREAD

**Issue by desilinguist** [tresoldi/dafsa#5]
It would be nice if you could create a [conda](https://conda.io/en/latest:) package and release it on anaconda.org. That would make it very easy for folks like me who prefer to use `conda` over `pip`.

**Comment by tresoldi** [comment]
Sure, and it would be a good practice, I've never created a conda package before.

I'll get to it once I'm finished with the other issues, and comment again here.

**Comment by tresoldi** [comment]
@desilinguist The package is online: https://anaconda.org/tresoldi/dafsa

Resources for the package were added with commit d39d83a9881ef7c083e593b384fd2772d5f434b5

Let me know if it is ok (as I commented above, it is the first time I build a conda package).

**Comment by desilinguist** [comment]
Thank you so much for taking up my suggestion! You might also want to add another badge to the README for the conda package.
