### ISSUE TITLE
Suggestion for improving community guidelines

### ISSUE THREAD

**Issue by geoffbacon** [tresoldi/dafsa#6]
I see the section in `README.md` on community guidelines but would like to suggest including more detailed instructions on contributing. For potential users and collaborators, especially those new to the field, clear instructions on e.g. submitting a bug or question on GitHub can be helpful. In addition, it will reduce the number of false or incomplete you'll receive. For example, see [TensorFlow's issue templates](https://github.com/tensorflow/tensorflow/tree/master/.github/ISSUE_TEMPLATE) or [Numpy's](https://github.com/numpy/numpy/tree/master/.github), or a contributing template like [this](https://gist.github.com/PurpleBooth/b24679402957c63ec426) or [this](https://github.com/nayafia/contributing-template).

**Comment by geoffbacon** [comment]
I don't think these are obligatory though, but would suggest that they are considered if they already haven't been.

**Comment by tresoldi** [comment]
It is a good practice, better to err in favour of having one.

I have added one in a different branch ([here](https://github.com/tresoldi/dafsa/blob/joss/CONTRIBUTING.md)), I'll comment again once I merge to `master`.

**Comment by tresoldi** [comment]
@geoffbacon it is now merged in `master` (file `CONTRIBUTING.md`, plus a note in the readme file), which is distributed with the new version 0.6. Please close the issue when ok.

**Comment by geoffbacon** [comment]
Looks great

**Comment by tresoldi** [comment]
Thank you!
